### ISSUE TITLE
bug 01

### ISSUE THREAD

**Issue by KarlCecilio** [iPolloverse/Test#1]
有节点存在长时间测量无返回，但是measureNetBandComplete消息已经返回

![image](https://user-images.githubusercontent.com/13198368/191154949-9449824f-9479-410b-87ed-c8f656e471e4.png)

**Comment by NGPU-AI** [comment]
fixed， nvidia-smi crashes occasionally during plotting disk. 
no calling nvida-smi when measuring. 
published in the morning on Sep 20, 2022. 1.0.23

**Comment by karlcecilio** [comment]
您好，您发的信件我已收到，感谢您的来信，我会尽快回复！ Best Regards!

**Comment by karlcecilio** [comment]
haha
