### ISSUE TITLE
bug 6 注意测试公链的端口问题

### ISSUE THREAD

**Issue by DExpress-dev** [iPolloverse/Test#6]
1：存在未知节点链接iPolloverse公链并请求同步节点数据但被公链拦截情况，原因应是使用的端口为默认端口。
![image](https://user-images.githubusercontent.com/77254888/191263090-32fd1e05-a91b-46b2-b66f-2b2721f8669a.png)

**Comment by NGPU-AI** [comment]
看起来是好事者采用标准以太坊接口进行试探
