### ISSUE TITLE
帐号注册成功后无法登录

### ISSUE THREAD

**Issue by kaigedong** [iPolloverse/Test#8]
点击登录时网页错误提示无法看出错误信息，

通过控制台看到：请求payload: {"username":"dongkaige@gmail.com","password":"****"}

Response: {"error":"Cannot read properties of undefined (reading 'password')"}

**Comment by kaigedong** [comment]
抱歉，我用邮箱登录了，应该用“用户名”登录

**Comment by karlcecilio** [comment]
您好，您发的信件我已收到，感谢您的来信，我会尽快回复！ Best Regards!
